sudo: enabled
language: node_js
node_js:
  - "6"
script:
  - npm install
  - unset CI
  - npm run build
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: 369558172@qq.com
  password:
    secure: "Y/1J/IaWTMYj2HwseTQImbqLeSY9V63L4Y5RzNd3HaAQnDhhkI8/UvxvVtdv6a1iryg1DtHizYpPOxsgPmdBf5D6/FYnKurmjTt9NmlodO4HIDlY7m/PwaxtpcwHjJe3Hn6RPMif1tqtPzT99Yh4v34WyFy7vv6m9aQHSaZnHj3vh/J3FJU6kcA1bEcu8rXpix8bP9ku4Z3GAu8ypUGlk02IzODpoLcviNMgl7Fm1qrVAt5C0rqMO4k/dPiDBsurKGiG5gc2ThAQwjz6hYIUz9WTfSzhqLcWDa5I4mWeDZZUQ94Q3qoqYgbE7sA3E+0gWm/V6XPB6g6IX5IYzmuOX1KPn3qMrbJcxUX/z7o2GbveI4mW5PjdYQts5ilywSz0/MweBgdQcT2U8p9WprS3V4mqvrk8I0aHG7TFvv7GHKldEKkcHIQO1aLiB4MFFRNC9CiQDJPfbWeqUZjBYj2j4bY76thneJIs8fD8xOTpGsVvSay556w0kEmhWESMuCMf303X5JIKO21i1cMjtoIB2tCQCTqxvQy2kTeUnTgA2PkMTONw9zew9YuQt+40I8vnXJDZvmAJdRuhU44cgdRK5hZODhX1CDAWMWbiTKzHdyl0MQl1Bb8U/2LD70frl9E0hf70FvzLOLajromQtTRYEErfW2NLIKnqdeT0+47ntOg="
  organization: morenbuou3
  space: reactShop
  on:
    repo: morenbuou3/ReactShop