language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm install
  - unset CI
  - npm run build
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: 369558172@qq.com
  password:
    secure: jdxcxKm6hgsozgzU/euZHvqzSAsDmKp6MwDtsWi4hPY7rRm71YJGimzspPC25FVoSoolPvu102evJS3RkotzzsAhnSIvyjUaR+FlQetjd1yUoT50NRrSOb+aIoXddqVsOZPqoz3BzcszgpSkBoOJrNlyTtUw4dutCxNBvB51K2l809IyjmsF34QcDhKuavsr4oJ6gJEhZX90vvr6a0of1qUDWHqX50JI2m8O8QP6mKkHZcmMiHiC+Fy2LZs3Oe/AbnaHdVmxUvtu1wy92oOCBeju7jqpLee6zabo79YyaV/C+ySuaQKOcHZZWQ7bvQmmZAEcSp+yiTcNk+rfD40vNzxgwv6s1q0PA3f0oarIHyEMj9jXLM46oaKXacun0gudOC2s48r40N6mqEAyoUS1YfJ5tYH58D2rITxaMOYBE6vGWCsmdU/hzWZRQqONP82+YC1PVtWZm4itr95SCZtGIkd75Wez9Wc7eTdGoraKh50+6MhKlQF9aYbZwR0TPpZSkxxVnjr/9Wpida+XHl0m6czre+mVcCtRW0qTiE2eg43M9CsUud1V5JqfrbRugIyXYEt6yrZXo0hOJEcYztBQSpuoDKHcjqVyYwsOoE8j5vPzw2VaXrzU3JoV/igOdGeeB44P3KncLOWihtWF7KzTLg8vHwCCv9gB8yyBVNTFyhM=
  organization: morenbuou3
  space: reactShop
  on:
    repo: morenbuou3/ReactShop